# Generated by Django 4.0.5 on 2022-07-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0003_auto_20220611_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='eye_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy.eyecolor'),
        ),
    ]
